file_format: "1"
id: cosmos-5x6
name: Cosmos-5x6
type: shield
url: https://github.com/TezzIRL/cosmos-5x6-shield-module
requires: [pro_micro]
features:
  - keys
siblings:
  - cosmos-5x6_left
  - cosmos-5x6_right